GET http://localhost:5000/

###

POST http://localhost:5000/ai/merge
Content-Type: application/json

[
  {
    "type": "image",
    "url": "https://demo.70e9f1a0f18a49a29a0cd16c9e0750df.lambdaspaces.com/file=/home/demo/source/ex2-3.jpeg",
    "strength": 3.2
  },
  {
    "type": "image",
    "url": "https://demo.70e9f1a0f18a49a29a0cd16c9e0750df.lambdaspaces.com/file=/home/demo/source/blonder.jpeg",
    "strength": 3
  },
  {
    "type": "text",
    "prompt": "central symmetric figure detailed artwork",
    "strength": 2
  },
  {
    "type": "nothing"
  }
]

###
POST http://localhost:5000/ai/merge
Content-Type: application/x-www-form-urlencoded
Host: localhost
User-Agent: HTTPie

type1=image&
string1=https://upload.wikimedia.org/wikipedia/commons/thumb/9/91/Bruce_McCandless_II_during_EVA_in_1984.jpg/1024px-Bruce_McCandless_II_during_EVA_in_1984.jpg&
rength1=3.2&
type2=image&
string2=https://lambdalabs-image-mixer-demo.hf.space/file=/home/user/app/ex2-3.jpeg&
rength2=3.&
type3=text&
string3=add+floating+cats&
strength3=2&
input4=nothing


###
